### ISSUE TITLE
Edit list of games

### ISSUE THREAD

**Issue by iimog** [iimog/x-game-master#5]
Make list of games editable. Add edit and remove games via game preferences:
 - [ ] Add new game (#8)
 - [ ] Edit existing game (#9)
 - [ ] Remove game (#10)
 - [ ] Reset game list (#11)
 - [ ] Copy game (useful to have the same game with default pre-settings)

**Comment by iimog** [comment]
No longer relevant after re-write (>=0.3.0)
